Fix mobile build for geth 1.9 (#865)
* Fix gosigar build error on iOS using our fork

libproc.h is not available on iOS

* Fix gobind build error on iOS due to different parameter names in the generated ObjC code of the Sign method between Signer and MobileSigner

Error was:
Geth_darwin.m:5082:17: error: method 'sign:p1:error:' in protocol 'GethSigner' not implemented [-Werror,-Wprotocol]

* Remove bitcode patch, bitcode is now disabled in gomobile for go < 1.14

See https://github.com/golang/mobile/commit/875e90d6f7e9368c509b72b05c4b1c0db3118351

* Make sure the right go version is installed

* Fix android dockerfile so it's simpler to use from circleci

* Simplify ios build step

Directly install the default rust toolchain

* No need to wait for build-geth to build ios and android