Fix gobind build error on iOS due to different parameter names in the generated ObjC code of the Sign method between Signer and MobileSigner
Error was:
Geth_darwin.m:5082:17: error: method 'sign:p1:error:' in protocol 'GethSigner' not implemented [-Werror,-Wprotocol]